---
title: "eds221-day4-interactive"
author: "carly"
format: html
editor: visual
---

## Functions

Make a function that doubles a value.

```{r}
double_value <- function(my_dollars){
  print(my_dollars * 2)
}
double_value(25)
double_value(my_dollars = 25)
```

```{r}
#We can create a vector of values and fun that through our function
monthly_income <- c(42.50, 61.75, 89.50)
double_value(monthly_income)
```

Create a function that returns an awesome restaurant name given a cool animal and your favorite food:

```{r}
name_restaurant <- function(animal, food){
  print(paste0(animal, food))
}

name_restaurant("rabbit", "soup")
```

Given temperature in degrees Fahrenheit, write a function that converts it to Celsius.

```{r}
temp_f_to_celsius <- function(fahrenheit){
  paste(.555 * (fahrenheit - 32))
}
temp_f_to_celsius(52)
```

Create a function that given inputs of age and hometown returns "I am \_years old and I am from \_"

```{r}
age_hometown <- function(age, hometown) {
  print(paste("I am", age, "years old and I am from", hometown))
}
age_hometown(age = 27, hometown = "Shelburne")
```

```{r}
#We also don't have to use print in the function because that is saying "show me this". We can just run the function and return and store the value as seen below. We can then reuse that stored value for calculations or in other work we are doing. 
double_value2 <- function(my_dollars){
  my_dollars * 2
}
double_value2(10) 
```

## 
